language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol
    token:
      secure: "TBgldGqY4/1dmwVHGANTkdjIUgKwVHPn5tHRBnLebwhu7jq3xabFZyZIRhvM8AXAMSHD2KOEmjAWfj46VjP8UeOUUFfb5waWtwxjJhhq5OuPSH9fGiMYyJ1Vccn+StThQUItTErs92x/YCmWEK/Z39cO7mqN7HXzwIAdL44SzzoN0VsCzavD7VkLI1k+0mbHsTHPfBownSpIJEPL1P8+SKDF2GPZZVCVh868S4XF2C/tUmtqvZ1O13+jyjLhrW0prMtFrHmprwLEJlpBEee1eEfQoN2dGBEk/T9UxsG/qV+vfjHAAzOK1/OedmYcHAH3jZRwOvDshDbW5DRnuIjG8B+BXHmNyzD511vasS8iA8wvtZbPb3aMaL4QpfTvgQH7go1J2xlUOx+ct4KlkqIq/5P82Gli1bWSTKmOtTDznhU3VGatWMBosx66MRukZXeO2EfsgqrLMpCIxjWU6nHL62EbDGegkf3ORq+S5dpNF2Grj0vOjZ74jeACw1ZpKFIw81ttPwc+8/sv5M2D3PYGN1u7HMmW9RTP4oGFdrh2d4FNn4cKdCyiRO1MQ1FojOkXiEgEhK3um4gyYRSvTaz8/Bs/sI52DSs9PztZk17CbcZAlC3vZKTqpO6OA3rZJCOByyI2EhqXYIa3NIk93ThIGMjxt5AW8W51JVaOLidvkuw="

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"