package com.exasol.autogeneratedresourceverifier;

import java.nio.file.Path;

public interface AutogeneratedResource {
    public String generateContent();

    public Path getPathOfGeneratedFile();
}
