package com.exasol.autogeneratedresourceverifier;

import java.io.File;
import java.io.IOException;
import java.nio.file.*;

import com.exasol.errorreporting.ExaError;

/**
 * This class verifies that an {@link AutogeneratedResource} has the expected value. In addition it can fix it.
 */
public class AutogeneratedResourceVerifier {
    /** Name of the property that enables fixing the autogenerated resources. */
    public static final String FIX_SYSTEM_PROPERTY = "fixAutogeneratedResources";
    /** Name of the property for the project directory. */
    public static final String PROJECT_DIR_SYSTEM_PROPERTY = "projectDir";

    /**
     * Verify that an {@link AutogeneratedResource} has the expected value.
     *
     * @param autogeneratedResource Autogenerated resource to check
     */
    public void verifyResource(final AutogeneratedResource autogeneratedResource) {
        final Path projectDir = readProjectDir();
        final String expected = autogeneratedResource.generateContent();
        final Path resourcePath = projectDir.resolve(autogeneratedResource.getPathOfGeneratedFile());
        if (isFixEnabled()) {
            overrideFile(expected, resourcePath);
        } else {
            validateFile(expected, resourcePath);
        }
    }

    private Path readProjectDir() {
        final String projectDirString = System.getProperty(PROJECT_DIR_SYSTEM_PROPERTY, "");
        if (projectDirString.equals("")) {
            throw new IllegalStateException(ExaError.messageBuilder("E-ARVJ-6")
                    .message("Missing property " + PROJECT_DIR_SYSTEM_PROPERTY + ".")
                    .mitigation(
                            "Please set the property to the absolute path of your projects root. Usually this is done using the exec-maven-plugin.")
                    .toString());
        }
        return Path.of(projectDirString);
    }

    private void validateFile(final String expected, final Path resourcePath) {
        assertResourceExists(resourcePath);
        final String actual = readResource(resourcePath);
        if (!expected.trim().equals(actual.trim())) {
            throw new IllegalStateException(
                    ExaError.messageBuilder("E-ARVJ-4").message("Autogenerated resource {{resource name}} is outdated.")
                            .parameter("resource name", resourcePath.toString())
                            .mitigation("You can enable automatic update by adding -D" + FIX_SYSTEM_PROPERTY + "=true.")
                            .toString());
        }
    }

    private void overrideFile(final String expected, final Path resourcePath) {
        try {
            createEnclosingDirectoryIfNotExists(resourcePath);
            Files.writeString(resourcePath, expected, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
        } catch (final IOException exception) {
            throw new IllegalStateException(ExaError.messageBuilder("E-ARVJ-5")
                    .message("Failed to write autogenerated resource {{resource name}}.")
                    .parameter("resource name", resourcePath.toString()).toString(), exception);
        }
    }

    private void createEnclosingDirectoryIfNotExists(final Path resourcePath) {
        final File directory = resourcePath.toFile().getParentFile();
        if (!directory.exists()) {
            if (!directory.mkdirs()) {
                throw new IllegalStateException(ExaError.messageBuilder("E-ARVJ-3")
                        .message("Failed to create directory {{directory name}} for autogenerated resource.")
                        .parameter("directory name", directory.toString()).toString());
            }
        }
    }

    private boolean isFixEnabled() {
        return System.getProperty(FIX_SYSTEM_PROPERTY, "").equals("true");
    }

    private void assertResourceExists(final Path resourcePath) {
        if (!resourcePath.toFile().exists()) {
            throw new IllegalStateException(
                    ExaError.messageBuilder("E-ARVJ-2").message("Autogenerated resource {{resource name}} is missing.")
                            .mitigation("Use -D" + FIX_SYSTEM_PROPERTY + "=true to create the missing File.")
                            .parameter("resource name", resourcePath.toString()).toString());
        }
    }

    private String readResource(final Path resourcePath) {
        try {
            return Files.readString(resourcePath);
        } catch (final IOException exception) {
            throw new IllegalStateException(ExaError.messageBuilder("E-ARVJ-1")
                    .message("Failed to read required resource {{resource name}} for verification.")
                    .parameter("resource name", resourcePath.toString()).toString(), exception);
        }
    }
}
