package com.exasol.autogeneratedresourceverifier;

import java.nio.file.Path;

/**
 * Interface for classes that define autogenerated resources. These resources are typically markdown files that are
 * dynamically generated from code.
 */
public interface AutogeneratedResource {

    /**
     * Get the generated content for the resource.
     * 
     * @return generated content
     */
    public String generateContent();

    /**
     * Path of the file that's content should be generated, relative to the projects directory.
     * 
     * @return path of the file
     */
    public Path getPathOfGeneratedFile();
}
